package com.nathanjones.planeaboveyou.model

object USStateBounds {
    private val bounds: Map<String, CountryBounds> = mapOf(
        "AL" to CountryBounds(minLat = 30.1, maxLat = 35.0, minLon = -88.6, maxLon = -84.8),
        "AK" to CountryBounds(minLat = 51.2, maxLat = 71.6, minLon = -179.2, maxLon = -129.9),
        "AZ" to CountryBounds(minLat = 31.3, maxLat = 37.0, minLon = -114.8, maxLon = -109.0),
        "AR" to CountryBounds(minLat = 33.0, maxLat = 36.5, minLon = -94.6, maxLon = -89.6),
        "CA" to CountryBounds(minLat = 32.5, maxLat = 42.0, minLon = -124.5, maxLon = -114.1),
        "CO" to CountryBounds(minLat = 37.0, maxLat = 41.0, minLon = -109.1, maxLon = -102.0),
        "CT" to CountryBounds(minLat = 40.9, maxLat = 42.1, minLon = -73.7, maxLon = -71.8),
        "DE" to CountryBounds(minLat = 38.4, maxLat = 39.9, minLon = -75.8, maxLon = -75.0),
        "FL" to CountryBounds(minLat = 24.4, maxLat = 31.0, minLon = -87.7, maxLon = -80.0),
        "GA" to CountryBounds(minLat = 30.4, maxLat = 35.0, minLon = -85.6, maxLon = -80.8),
        "HI" to CountryBounds(minLat = 18.9, maxLat = 22.3, minLon = -160.3, maxLon = -154.7),
        "ID" to CountryBounds(minLat = 42.0, maxLat = 49.1, minLon = -117.3, maxLon = -111.0),
        "IL" to CountryBounds(minLat = 36.9, maxLat = 42.5, minLon = -91.6, maxLon = -87.5),
        "IN" to CountryBounds(minLat = 37.8, maxLat = 41.8, minLon = -88.1, maxLon = -84.8),
        "IA" to CountryBounds(minLat = 40.4, maxLat = 43.6, minLon = -96.7, maxLon = -90.1),
        "KS" to CountryBounds(minLat = 37.0, maxLat = 40.0, minLon = -102.1, maxLon = -94.6),
        "KY" to CountryBounds(minLat = 36.5, maxLat = 39.2, minLon = -89.6, maxLon = -81.9),
        "LA" to CountryBounds(minLat = 28.9, maxLat = 33.1, minLon = -94.1, maxLon = -88.8),
        "ME" to CountryBounds(minLat = 43.0, maxLat = 47.5, minLon = -71.1, maxLon = -66.9),
        "MD" to CountryBounds(minLat = 37.9, maxLat = 39.7, minLon = -79.6, maxLon = -75.0),
        "MA" to CountryBounds(minLat = 41.2, maxLat = 42.9, minLon = -73.6, maxLon = -69.9),
        "MI" to CountryBounds(minLat = 41.7, maxLat = 48.3, minLon = -90.5, maxLon = -82.1),
        "MN" to CountryBounds(minLat = 43.5, maxLat = 49.4, minLon = -97.3, maxLon = -89.5),
        "MS" to CountryBounds(minLat = 30.2, maxLat = 35.0, minLon = -91.7, maxLon = -88.1),
        "MO" to CountryBounds(minLat = 36.0, maxLat = 40.6, minLon = -95.8, maxLon = -89.1),
        "MT" to CountryBounds(minLat = 44.4, maxLat = 49.1, minLon = -116.1, maxLon = -104.0),
        "NE" to CountryBounds(minLat = 40.0, maxLat = 43.1, minLon = -104.1, maxLon = -95.3),
        "NV" to CountryBounds(minLat = 35.0, maxLat = 42.0, minLon = -120.1, maxLon = -114.0),
        "NH" to CountryBounds(minLat = 42.7, maxLat = 45.3, minLon = -72.6, maxLon = -70.6),
        "NJ" to CountryBounds(minLat = 38.9, maxLat = 41.4, minLon = -75.6, maxLon = -73.9),
        "NM" to CountryBounds(minLat = 31.3, maxLat = 37.0, minLon = -109.1, maxLon = -103.0),
        "NY" to CountryBounds(minLat = 40.5, maxLat = 45.1, minLon = -79.8, maxLon = -71.8),
        "NC" to CountryBounds(minLat = 33.8, maxLat = 36.7, minLon = -84.4, maxLon = -75.4),
        "ND" to CountryBounds(minLat = 45.9, maxLat = 49.1, minLon = -104.1, maxLon = -96.5),
        "OH" to CountryBounds(minLat = 38.4, maxLat = 42.4, minLon = -84.9, maxLon = -80.5),
        "OK" to CountryBounds(minLat = 33.6, maxLat = 37.1, minLon = -103.1, maxLon = -94.4),
        "OR" to CountryBounds(minLat = 42.0, maxLat = 46.3, minLon = -124.7, maxLon = -116.5),
        "PA" to CountryBounds(minLat = 39.7, maxLat = 42.6, minLon = -80.6, maxLon = -74.7),
        "RI" to CountryBounds(minLat = 41.1, maxLat = 42.0, minLon = -71.9, maxLon = -71.1),
        "SC" to CountryBounds(minLat = 32.0, maxLat = 35.2, minLon = -83.4, maxLon = -78.5),
        "SD" to CountryBounds(minLat = 42.5, maxLat = 45.9, minLon = -104.1, maxLon = -96.4),
        "TN" to CountryBounds(minLat = 35.0, maxLat = 36.7, minLon = -90.4, maxLon = -81.6),
        "TX" to CountryBounds(minLat = 25.8, maxLat = 36.6, minLon = -106.7, maxLon = -93.5),
        "UT" to CountryBounds(minLat = 37.0, maxLat = 42.0, minLon = -114.1, maxLon = -109.0),
        "VT" to CountryBounds(minLat = 42.7, maxLat = 45.1, minLon = -73.5, maxLon = -71.5),
        "VA" to CountryBounds(minLat = 36.5, maxLat = 39.5, minLon = -83.7, maxLon = -75.2),
        "WA" to CountryBounds(minLat = 45.5, maxLat = 49.1, minLon = -124.9, maxLon = -116.9),
        "WV" to CountryBounds(minLat = 37.2, maxLat = 40.7, minLon = -82.7, maxLon = -77.7),
        "WI" to CountryBounds(minLat = 42.5, maxLat = 47.4, minLon = -92.9, maxLon = -86.2),
        "WY" to CountryBounds(minLat = 41.0, maxLat = 45.1, minLon = -111.1, maxLon = -104.0),
        "DC" to CountryBounds(minLat = 38.79, maxLat = 38.995, minLon = -77.12, maxLon = -76.91)
    )

    private val neighboringStates: Map<String, List<String>> = mapOf(
        "AL" to listOf("FL", "GA", "MS", "TN"),
        "AK" to emptyList(),
        "AZ" to listOf("CA", "NV", "UT", "CO", "NM"),
        "AR" to listOf("MO", "TN", "MS", "LA", "TX", "OK"),
        "CA" to listOf("OR", "NV", "AZ"),
        "CO" to listOf("WY", "NE", "KS", "OK", "NM", "AZ", "UT"),
        "CT" to listOf("NY", "MA", "RI"),
        "DE" to listOf("MD", "NJ", "PA"),
        "FL" to listOf("AL", "GA"),
        "GA" to listOf("FL", "AL", "TN", "NC", "SC"),
        "HI" to emptyList(),
        "ID" to listOf("WA", "OR", "NV", "UT", "WY", "MT"),
        "IL" to listOf("WI", "IA", "MO", "KY", "IN"),
        "IN" to listOf("MI", "OH", "KY", "IL"),
        "IA" to listOf("MN", "SD", "NE", "MO", "IL", "WI"),
        "KS" to listOf("NE", "MO", "OK", "CO"),
        "KY" to listOf("IL", "IN", "OH", "WV", "VA", "TN", "MO"),
        "LA" to listOf("TX", "AR", "MS"),
        "ME" to listOf("NH"),
        "MD" to listOf("VA", "WV", "PA", "DE", "DC"),
        "MA" to listOf("RI", "CT", "NY", "VT", "NH"),
        "MI" to listOf("WI", "IN", "OH"),
        "MN" to listOf("ND", "SD", "IA", "WI"),
        "MS" to listOf("LA", "AR", "TN", "AL"),
        "MO" to listOf("IA", "IL", "KY", "TN", "AR", "OK", "KS", "NE"),
        "MT" to listOf("ID", "WY", "SD", "ND"),
        "NE" to listOf("SD", "IA", "MO", "KS", "CO", "WY"),
        "NV" to listOf("OR", "ID", "UT", "AZ", "CA"),
        "NH" to listOf("ME", "MA", "VT"),
        "NJ" to listOf("NY", "PA", "DE"),
        "NM" to listOf("AZ", "UT", "CO", "OK", "TX"),
        "NY" to listOf("PA", "NJ", "CT", "MA", "VT"),
        "NC" to listOf("VA", "TN", "GA", "SC"),
        "ND" to listOf("MT", "SD", "MN"),
        "OH" to listOf("PA", "WV", "KY", "IN", "MI"),
        "OK" to listOf("CO", "KS", "MO", "AR", "TX", "NM"),
        "OR" to listOf("WA", "ID", "NV", "CA"),
        "PA" to listOf("NY", "NJ", "DE", "MD", "WV", "OH"),
        "RI" to listOf("CT", "MA"),
        "SC" to listOf("NC", "GA"),
        "SD" to listOf("ND", "MN", "IA", "NE", "WY", "MT"),
        "TN" to listOf("KY", "VA", "NC", "GA", "AL", "MS", "AR", "MO"),
        "TX" to listOf("NM", "OK", "AR", "LA"),
        "UT" to listOf("ID", "WY", "CO", "NM", "AZ", "NV"),
        "VT" to listOf("NY", "NH", "MA"),
        "VA" to listOf("NC", "TN", "KY", "WV", "MD", "DC"),
        "WA" to listOf("ID", "OR"),
        "WV" to listOf("OH", "PA", "MD", "VA", "KY"),
        "WI" to listOf("MI", "MN", "IA", "IL"),
        "WY" to listOf("MT", "SD", "NE", "CO", "UT", "ID"),
        "DC" to listOf("MD", "VA")
    )

    fun boundsForStateAndNeighbors(stateCode: String): CountryBounds? {
        val state = stateCode.uppercase()
        val own = bounds[state] ?: return null
        val neighbors = neighboringStates[state] ?: emptyList()
        val allBounds = (listOf(state) + neighbors).mapNotNull { bounds[it] }
        if (allBounds.isEmpty()) return own
        return CountryBounds(
            minLat = allBounds.minOf { it.minLat },
            maxLat = allBounds.maxOf { it.maxLat },
            minLon = allBounds.minOf { it.minLon },
            maxLon = allBounds.maxOf { it.maxLon }
        )
    }
}
